# SDRplay RSP1 configuration for soapysdr_to_direwolf.py
# Adjust IFGR (20=more gain, 59=less) and RFGR (0=more gain, 3=less)

DEVICE driver=sdrplay
FREQUENCY 144.800
SAMPLE_RATE 192000
AGC false
GAIN IFGR 35
GAIN RFGR 0
